Fix issue 622
w3c/json-ld-api pull request #623
Opened 2024-12-14 01:06 UTC by multimeric

Closes #622.

2025-01-15 17:25 UTC, TallTed commented on index.html
> +          <code>+json</code> suffix as defined in [[RFC6839]], reject the <var>promise</var> passing a <a data-link-for="JsonLdErrorCode">loading document failed</a> error.</li>
```suggestion
          <code>+json</code> suffix as defined in [[RFC6839]],
          reject the <var>promise</var> passing a <a data-link-for="JsonLdErrorCode">loading document failed</a> error.</li>
```

2025-01-16 11:06 UTC, pchampin commented
thanks @multimeric for the IPR commitment.
@BigBlueHat @gkellogg we are good to move forward with this PR.

2025-01-25 23:30 UTC, gkellogg approved these changes
I added Candidate Correction markup and a log entry.

2025-01-27 13:10 UTC, pchampin requested changes
There is a spurious change in the "changelog" section, which should be removed from this PR.
Otherwise, LGTM.

2025-01-27 13:10 UTC, pchampin commented on index.html
> +      as described in <a href="#change_5">Candidate Correction 5</a>.</li>
```suggestion
```
I suspect this has leaked from another PR, right?
It should probably be removed from that one.

2025-01-27 13:43 UTC, multimeric commented on index.html
> +      as described in <a href="#change_5">Candidate Correction 5</a>.</li>
This was added in 3b0a95c which I didn't make. Do you want me to fix it?

2025-01-27 16:26 UTC, gkellogg commented on index.html
> +      as described in <a href="#change_5">Candidate Correction 5</a>.</li>
I added it to simplify a future merge, otherwise, it will lead to a conflict. If we do the PRs in an appropriate order, these will mesh together.

2025-01-27 22:41 UTC, merged